"""
Shared State Definition
=======================
Defines the shared state schema for the LangGraph workflow.
All agents read from and write to this state as it flows
through the graph.
"""

from typing import Annotated, TypedDict
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    The shared state that flows through the LangGraph cybersecurity pipeline.

    Attributes:
        messages: Conversation messages accumulated across agents.
        target: The IP/hostname being investigated.
        target_ip: The specific IP address to scan (used by recon_node).
        scan_results: Raw results from Nmap/network scanning.
        web_tech_results: Web technology fingerprinting results from
            ``scan_web_tech`` — detected server software, frameworks,
            JS libraries, CMS platforms, and security header audit.
        incident_report: Running incident report that each agent appends to.
        log_data: Raw log data for analysis.
        threat_analysis: Threat analysis findings and risk assessment.
        threat_analysis_report: Structured threat analysis report string
            produced by the Threat Analysis Agent (Senior SOC Analyst).
        threat_summary: Plain-English one-paragraph summary of the key threats,
            MITRE ATT&CK techniques identified, and recommended immediate actions.
            Populated by the Threat Analysis Agent.
        threat_detected: True when the analysis agent assigns a risk_score > 7.
        threat_intel_context: Relevant threat intel retrieved from the vector DB.
        response_plan: Incident response plan generated by the Response Agent.
        risk_level: Overall risk level (CRITICAL, HIGH, MEDIUM, or LOW).
        risk_score: Numeric risk score from 0 (no risk) to 10 (critical).
        category: Threat category (e.g. 'Information Disclosure', 'Unauthenticated Access').
        final_decision: Human-approval status set by the Response Agent.
        final_remediation_plan: Structured technical remediation plan with
            executable commands (iptables rules, AWS SG updates, etc.)
            logged by the Response Agent.
        stealth_mode: When ``True`` the Recon Agent uses a SYN Stealth
            scan (``-sS -T2 -f``) instead of the default service-version
            scan (``-sV``).  This avoids detection by simple firewalls
            and IDS/IPS systems at the cost of less version information.
        dry_run: When ``True`` (default) the Action Executor simulates
            every remediation command without actually running it —
            safe for all environments.  Set to ``False`` only after the
            human operator explicitly enables "Live Execution" in the UI
            or passes ``--live`` on the CLI.
        execution_results: List of ExecutionResult dicts produced by the
            Action Executor tool.  Each entry records the command, its
            dry_run flag, status (DRY_RUN | SUCCESS | FAILED | TIMEOUT |
            BLOCKED | ERROR), returncode, stdout, stderr, and wall-clock
            duration in milliseconds.  Empty list when no commands have
            been executed yet (e.g. LOW/MEDIUM risk, or before approval).
        current_agent: Name of the currently active agent.
        confidence_score: A float between 0.0 and 1.0 representing the
            agent's confidence in its assessment.  Used by the routing
            logic to decide whether to auto-execute the response plan
            (high confidence) or require human review (lower confidence).
        incident_logs: A list of free-form strings that each agent
            appends to as it reasons through its steps.  Provides an
            internal audit trail of agent decision-making for the final
            incident report.
        raw_log_data: The initial raw log / alert payload that triggered
            the pipeline, typically forwarded by the Monitor component.
        is_vulnerable: Boolean flag set by the Investigate / Recon node
            indicating whether the target was found to have exploitable
            vulnerabilities.
    """

    messages: Annotated[list, add_messages]
    target: str
    target_ip: str
    scan_results: dict
    web_tech_results: dict
    incident_report: str
    log_data: str
    threat_analysis: dict
    threat_analysis_report: str
    threat_summary: str
    threat_detected: bool
    threat_intel_context: str
    response_plan: str
    risk_level: str
    risk_score: int
    category: str
    final_decision: str
    final_remediation_plan: str
    stealth_mode: bool
    dry_run: bool
    execution_results: list
    current_agent: str
    confidence_score: float
    incident_logs: list[str]
    raw_log_data: str
    is_vulnerable: bool
